name: Build and Publish Docker Image

# Este workflow é acionado sempre que um novo release for criado
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jogo-do-galo:${{ github.sha }} .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jogo-do-galo:${{ github.sha }}

      # Step 5: Tag the image with release version
      - name: Tag Docker image with release version
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/jogo-do-galo:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/jogo-do-galo:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/jogo-do-galo:${{ github.ref_name }}
